services:
  open-webui:
    image: ${WEBUI_IMAGE:-ghcr.io/nanashiwang/open-webui}:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "${OPEN_WEBUI_PORT:-3000}:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY:?WEBUI_SECRET_KEY is required}
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui:
    name: open-webui
